services:
  - type: web
    name: taskflow-backend
    runtime: python
    pythonVersion: "3.12"
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn taskflow.wsgi:application"
    envVars:
      - key: SQLITECLOUD_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "taskflow-backend.onrender.com"