# Generated by Django 6.0.3 on 2026-03-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeDue',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
