# Generated by Django 6.0.3 on 2026-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahoy_app', '0004_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='report_status',
            field=models.CharField(choices=[('none', 'None'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default='none', max_length=20),
        ),
    ]
